name: multiplex
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flame: ^1.23.0
  get: ^4.6.6
  get_storage: ^2.1.1
  intl: ^0.19.0

  # Games API integration
  games_api:
    path: ../packages/games_api

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/levels.json
