version: '3.8'

services:
  # Games API Service
  api:
    build: .
    container_name: games-api
    ports:
      - "8100:8100"
    environment:
      - ENV=production
      - SERVER_PORT=8100
      - DB_DRIVER=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=base_games
      - DB_PASSWORD=${DB_PASSWORD:-secure_password_change_me}
      - DB_NAME=base_games
      - JWT_SECRET=${JWT_SECRET:-change_me_in_production}
      - API_KEY=${API_KEY:-change_me_in_production}
      - CORS_ALLOWED_ORIGINS=https://multiplex.base.al,https://games.base.al
      - MIDDLEWARE_AUTH_ENABLED=true
      - MIDDLEWARE_CORS_ENABLED=true
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - games-network

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: games-db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root_password_change_me}
      - MYSQL_DATABASE=base_games
      - MYSQL_USER=base_games
      - MYSQL_PASSWORD=${DB_PASSWORD:-secure_password_change_me}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: unless-stopped
    networks:
      - games-network

networks:
  games-network:
    driver: bridge

volumes:
  mysql_data:
